/**
 * Transaction types for Paystack integration
 */

import { Timestamp } from 'firebase-admin/firestore';

export interface Transaction {
  id: string; // Firestore document ID
  
  // Reference
  reference: string; // Paystack transaction reference
  paystackReference: string; // Duplicate for clarity
  
  // Parties
  buyerId: string;
  buyerEmail: string;
  sellerId: string;
  sellerName: string;
  
  // Product
  productId: string;
  productName: string;
  productType: 'pattern' | 'physical';
  
  // Amounts (in kobo/smallest currency unit)
  amountKobo: number;
  platformFeeKobo: number;
  sellerGrossKobo: number;
  
  // Currency
  currency: string; // ZAR, NGN, GHS, KES, USD
  
  // Paystack specific
  paystackAccessCode?: string;
  paystackAuthorizationUrl?: string;
  paystackAuthorization?: PaystackAuthorization;
  paystackChannel?: string; // card, bank, ussd, qr, mobile_money
  paystackTransactionId?: number; // Paystack internal ID
  paystackFees?: number; // Paystack transaction fees in kobo
  paystackCustomerCode?: string;
  
  // Status
  status: 'pending' | 'success' | 'failed' | 'abandoned';
  paymentStatus: 'pending' | 'paid' | 'failed';
  
  // Gateway response
  gatewayResponse?: string;
  message?: string;
  
  // Timestamps
  createdAt: Timestamp;
  paidAt?: Timestamp;
  updatedAt: Timestamp;
  
  // Metadata
  metadata?: Record<string, any>;
  
  // Migration tracking (for historical Stripe data)
  migratedFrom?: 'stripe';
  stripePaymentIntentId?: string;
  stripeSessionId?: string;
}

export interface PaystackAuthorization {
  authorization_code: string;
  bin: string;
  last4: string;
  exp_month: string;
  exp_year: string;
  channel: string;
  card_type: string;
  bank: string;
  country_code: string;
  brand: string;
  reusable: boolean;
  signature: string;
  account_name?: string | null;
}

export interface WebhookLog {
  id: string; // Firestore document ID
  eventId: string; // Paystack event ID (for idempotency)
  eventType: string; // charge.success, transfer.success, etc.
  payload: any;
  processed: boolean;
  processedAt?: Timestamp;
  error?: string;
  retryCount?: number;
  createdAt: Timestamp;
}

export interface PlatformEarnings {
  id: string;
  
  // Transaction reference
  transactionId: string; // Firestore transaction doc ID
  reference: string; // Paystack reference
  
  // Amounts (in kobo)
  amount: number;
  applicationFee: number;
  currency: string;
  
  // Seller
  sellerId: string;
  sellerName: string;
  
  // Provider
  provider: 'stripe' | 'paystack';
  
  // Paystack specific
  paystackChargeId?: string;
  paystackSubaccountCode?: string;
  
  // Timestamps
  createdAt: Timestamp;
  
  // Metadata
  metadata?: Record<string, any>;
}

export interface SellerPayout {
  id: string;
  
  // Seller
  sellerId: string;
  sellerName: string;
  sellerEmail: string;
  
  // Amount (in kobo)
  amountKobo: number;
  currency: string;
  
  // Paystack specific
  paystackTransferCode?: string;
  paystackTransferId?: number;
  paystackRecipientCode: string;
  
  // Status
  status: 'pending' | 'processing' | 'success' | 'failed' | 'reversed';
  
  // Failure
  failureReason?: string;
  failureMessage?: string;
  
  // Reconciliation
  transactionIds: string[]; // Array of transaction IDs included in payout
  transactionCount: number;
  
  // Timestamps
  createdAt: Timestamp;
  processedAt?: Timestamp;
  completedAt?: Timestamp;
  
  // Metadata
  metadata?: Record<string, any>;
}

export interface ReconciliationReport {
  id: string;
  
  // Period
  startDate: Timestamp;
  endDate: Timestamp;
  
  // Summary
  totalTransactions: number;
  successfulTransactions: number;
  failedTransactions: number;
  
  // Amounts (in kobo)
  totalAmountKobo: number;
  totalPlatformFeesKobo: number;
  totalSellerEarningsKobo: number;
  
  // Mismatches
  mismatches: ReconciliationMismatch[];
  mismatchCount: number;
  
  // Status
  status: 'in_progress' | 'completed' | 'failed';
  
  // Timestamps
  createdAt: Timestamp;
  completedAt?: Timestamp;
  
  // Generated by
  generatedBy?: string; // User ID or 'system'
  
  // Report file
  reportUrl?: string; // CSV/PDF export URL
}

export interface ReconciliationMismatch {
  transactionId: string;
  reference: string;
  type: 'missing_in_paystack' | 'missing_in_firestore' | 'amount_mismatch' | 'status_mismatch';
  firestoreData?: Partial<Transaction>;
  paystackData?: any;
  difference?: {
    field: string;
    firestoreValue: any;
    paystackValue: any;
  };
  resolved: boolean;
  resolvedAt?: Timestamp;
  notes?: string;
}

export interface CreateTransactionParams {
  buyerId: string;
  buyerEmail: string;
  sellerId: string;
  sellerName: string;
  productId: string;
  productName: string;
  productType: 'pattern' | 'physical';
  amountKobo: number;
  currency?: string;
  metadata?: Record<string, any>;
}

export interface TransactionUpdateParams {
  status?: 'pending' | 'success' | 'failed' | 'abandoned';
  paymentStatus?: 'pending' | 'paid' | 'failed';
  paystackAuthorization?: PaystackAuthorization;
  paystackChannel?: string;
  paystackTransactionId?: number;
  paystackFees?: number;
  gatewayResponse?: string;
  message?: string;
  paidAt?: Timestamp;
}

// API Response types
export interface TransactionCreateResult {
  success: boolean;
  message?: string;
  transaction?: Transaction;
  authorizationUrl?: string;
  accessCode?: string;
  reference?: string;
}

export interface TransactionVerifyResult {
  success: boolean;
  message?: string;
  transaction?: Transaction;
  paystackData?: any;
}

export interface PayoutCreateResult {
  success: boolean;
  message?: string;
  payout?: SellerPayout;
}

export interface ReconciliationResult {
  success: boolean;
  message?: string;
  report?: ReconciliationReport;
}

export {};
